libxmldiff: errors.h File Reference
errors.h File Reference
#include "libxmldiff.h"
#include <exception>
Data Structures
class XD_Exception
Functions
void LIBXMLDIFF_API throwError (int type, const char *str,...)
XML Diff Exception Helper Function.
void LIBXMLDIFF_API verbose (int prio, int level, char *str,...)
Function Documentation
void LIBXMLDIFF_API throwError (int type, const char * str, ...)
XML Diff Exception Helper Function.
Definition at line 40 of file errors.cpp.
Referenced by applyStylesheet(), deleteNodes(), diffNode(), diffTree(), diffXmlFiles(), duplicateDocument(), executeAction(), executeFile(), getXmlFile(), getXsltFile(), loadXmlFile(), parseAction(), parseCommandLine(), and parseOption().
void LIBXMLDIFF_API verbose (int prio, int level, char * str, ...)
Definition at line 51 of file errors.cpp.
Referenced by applyStylesheet(), closeXmlFile(), deleteNodes(), diffXmlFiles(), duplicateDocument(), executeAction(), executeFile(), loadXmlFile(), main(), recalcXmlFiles(), saveXmlFile(), xmlFinalize(), and xmlInitialize().