libxmldiff: xmldiff.cpp File Reference
xmldiff.cpp File Reference
#include "xmldiff.h"
#include "errors.h"
Macros
#define stricmp strcmp
Functions
void cbPrintProgressionBar (int percent, int prec, long nbNodesBefore, long nbNodesAfter, long nbNodesProcessed, void *arg)
Standart Progression bar callback.
int main (int argc, char *argv[])
Main function : The main function :
Variables
struct appCommand curOptions
Macro Definition Documentation
#define stricmp strcmp
Definition at line 54 of file xmldiff.cpp.
Function Documentation
void cbPrintProgressionBar (int percent, int prec, long nbNodesBefore, long nbNodesAfter, long nbNodesProcessed, void * arg)
Standart Progression bar callback.
Definition at line 62 of file xmldiff.cpp.
Referenced by main().
int main (int argc, char * argv[])
Main function : The main function :
parse the command line
adjust some parameters
load / clean XML files
call the diff function
write the result
Definition at line 102 of file xmldiff.cpp.
References appCommand::action, xmldiff_options::callbackProgressionPercent, cbPrintProgressionBar(), curOptions, executeAction(), flushXmlFiles(), XD_Exception::getType(), parseCommandLine(), setDefaultXmldiffOptions(), usage(), verbose(), globalOptions::verboseLevel, XD_Exception::what(), XD_NONE, XMLDIFF_VER, xmlFinalize(), and xmlInitialize().
Variable Documentation
struct appCommand curOptions
Definition at line 57 of file xmldiff.cpp.
Referenced by main().