libxmldiff: lx2_util.h File Reference
lx2_util.h File Reference
#include "libxmldiff.h"
#include "lx2_str.h"
#include <libxml/parser.h>
#include <vector>
Functions
xmlstring LIBXMLUTIL_API getNodeTextOnly (xmlNodePtr node, bool cdata=false)
getNodeTextOnly Get text of the current node, without taking subnodes as does get_text()
xmlNodePtr LIBXMLUTIL_API getFirstChildByTagName (xmlNodePtr node, const xmlstring name)
getFirstChildByTagName Returns the first child of the children list having its tag name equal to the one provided
void LIBXMLUTIL_API setAttributeToAllChilds (const xmlNodePtr node, const xmlstring &ns, const xmlstring &name, const xmlstring &value, const bool toAll=true)
setAttributeToAllChilds Set the provided property to all children of the current element.
void LIBXMLUTIL_API cleanEmptyNodes (xmlNodePtr node)
cleanEmptyNodes Clean empty nodes from the tree.
void LIBXMLUTIL_API cleanPrivateTag (xmlNodePtr node)
cleanPrivateTag Set to NULL the _private tag of all nodes of the tree.
long LIBXMLUTIL_API countElementNodes (xmlNodePtr node)
countNodes Count the number of element nodes
int LIBXMLUTIL_API createNamespaceOnTop (xmlNodePtr node, const xmlChar *href, const xmlChar *prefix)
createNamespaceOnTop Create the namespace on top of document of the provided node
bool LIBXMLUTIL_API matchNode (xmlNodePtr node, vector< xmlstring > list)
matchNode Check if a given node matched a lists of names
Function Documentation
void LIBXMLUTIL_API cleanEmptyNodes (xmlNodePtr node)
cleanEmptyNodes Clean empty nodes from the tree.
Exists only to provide a workaround for the CRLFCRLF problem in DOS mode
Parameters
node the tree to be cleaned
cleanEmptyNodes Clean empty nodes from the tree.
Definition at line 90 of file lx2_util.cpp.
References cleanEmptyNodes().
Referenced by cleanEmptyNodes(), and loadXmlFile().
void LIBXMLUTIL_API cleanPrivateTag (xmlNodePtr node)
cleanPrivateTag Set to NULL the _private tag of all nodes of the tree.
Parameters
node the tree to be cleaned
cleanPrivateTag Set to NULL the _private tag of all nodes of the tree.
Definition at line 127 of file lx2_util.cpp.
References cleanPrivateTag().
Referenced by cleanPrivateTag().
long LIBXMLUTIL_API countElementNodes (xmlNodePtr node)
countNodes Count the number of element nodes
Parameters
node the node to count
Returns
the number of elements
countNodes Count the number of element nodes
Definition at line 141 of file lx2_util.cpp.
References countElementNodes().
Referenced by countElementNodes(), and diffTree().
int LIBXMLUTIL_API createNamespaceOnTop (xmlNodePtr node, const xmlChar * href, const xmlChar * prefix)
createNamespaceOnTop Create the namespace on top of document of the provided node
Parameters
node the node
href the href of the namespace to create
prefix the prefix to use in this document for this namespace
Returns
the number of successfully created namespace To get the created namespace, use searchNamespace...
Definition at line 163 of file lx2_util.cpp.
Referenced by diffTree().
xmlNodePtr LIBXMLUTIL_API getFirstChildByTagName (xmlNodePtr node, const xmlstring name)
getFirstChildByTagName Returns the first child of the children list having its tag name equal to the one provided
Parameters
node the node to search within children
name the name of the searched element
Returns
the pointer to the node (NULL if not found)
getFirstChildByTagName Returns the first child of the children list having its tag name equal to the one provided
Definition at line 52 of file lx2_util.cpp.
Referenced by populate_itemlist().
xmlstring LIBXMLUTIL_API getNodeTextOnly (xmlNodePtr node, bool cdata)
getNodeTextOnly Get text of the current node, without taking subnodes as does get_text()
Parameters
node concerned node
cdata if true, return also CDATA contents
Returns
the string contained in direct textnodes of the current node.
getNodeTextOnly Get text of the current node, without taking subnodes as does get_text()
Definition at line 27 of file lx2_util.cpp.
Referenced by diffNode(), and populate_itemlist().
bool LIBXMLUTIL_API matchNode (xmlNodePtr node, vector< xmlstring > list)
matchNode Check if a given node matched a lists of names
Parameters
node the node to match
list list of match expressions (no XPath nor regex for now)
Returns
true if the node matches
Definition at line 183 of file lx2_util.cpp.
Referenced by diffNode(), and populate_itemlist().
void LIBXMLUTIL_API setAttributeToAllChilds (const xmlNodePtr node, const xmlstring & ns, const xmlstring & name, const xmlstring & value, const bool toAll)
setAttributeToAllChilds Set the provided property to all children of the current element.
Parameters
node the concerned node
ns the namespace of the property
name the name of the property to add
value the value of the property to set
toAll if set to false, do not recurse
setAttributeToAllChilds Set the provided property to all children of the current element.
Definition at line 70 of file lx2_util.cpp.
References setAttributeToAllChilds().
Referenced by diffNode(), and setAttributeToAllChilds().