libxmldiff: lx2_parse.cpp File Reference
lx2_parse.cpp File Reference
#include "libxmldiff.h"
#include "lx2_parse.h"
#include "lx2_str.h"
#include "errors.h"
#include <string.h>
#include <iostream>
#include <sstream>
#include <fstream>
#include <vector>
Macros
#define stricmp strcmp
#define OPT_MATCH(x) (stricmp(option.c_str(), x) == 0)
#define ARG_MATCH(x) (stricmp(arg.c_str(), x) == 0)
#define ONE status = 1;
#define TWO_BOOL(x)
#define TWO
#define ACTION_MATCH(x) (stricmp(action.c_str(), x) == 0)
#define ARG_MATCH(x) (stricmp(cl[curarg].c_str(), x) == 0)
#define IS_BLANK(x) ((x == ' ') || (x == '\t') || (x == '\n') || (x == '\r'))
Functions
void splitVector (const string arg, vector< xmlstring > &v)
Split a string into a vector.
string joinVector (const vector< xmlstring > &v)
Join a vector into a string.
int parseOption (const string &option, const string &arg, struct globalOptions &opt)
parseOption : parse option item
int parseAction (string action, struct appCommand &cmd)
parseAction : parse action item
int parseCommandLine (const vector< string > &cl, struct appCommand &opt)
parseCommandLine : parse command line
int executeAction (const struct appCommand &p_cmd)
Execute an action from the command line.
vector< string > tokenizeCommand (string command)
tokenizeCommand : parse command line
int replaceTokens (vector< string > &tokens, map< string, string > variables)
Replace tokens by other values.
int executeFile (string scriptFileName, const map< string, string > &variables, const struct globalOptions &gOptions)
Execute file.
void usage ()
Print usage.
void printConfiguration (const struct globalOptions &opt)
Dump current configuration.
Macro Definition Documentation
#define ACTION_MATCH (x) (stricmp(action.c_str(), x) == 0)
Referenced by parseAction().
#define ARG_MATCH (x) (stricmp(arg.c_str(), x) == 0)
Referenced by parseCommandLine().
#define ARG_MATCH (x) (stricmp(cl[curarg].c_str(), x) == 0)
#define IS_BLANK (x) ((x == ' ') || (x == '\t') || (x == '\n') || (x == '\r'))
Referenced by tokenizeCommand().
#define ONE status = 1;
#define OPT_MATCH (x) (stricmp(option.c_str(), x) == 0)
Referenced by parseOption().
#define stricmp strcmp
Definition at line 36 of file lx2_parse.cpp.
#define TWO
Value:
if (arg == "") \
                { \
            throwError(XD_Exception::XDE_MISSING_ARG, "Missing argument to option '%s'.", option.c_str()); \
                } \
                else status = 2;
Referenced by parseOption().
#define TWO_BOOL (x)
Value:
if (ARG_MATCH("yes") || ARG_MATCH("1") || ARG_MATCH("oui") || \
                      ARG_MATCH("no") || ARG_MATCH("0") || ARG_MATCH("non") ) \
                { \
                        status = 2; \
                        if (ARG_MATCH("yes") || ARG_MATCH("1") || ARG_MATCH("oui")) argBool = true; \
                } \
                else \
                { \
                        status = 1; \
                        argBool = true; \
                } \
                x = argBool;
Referenced by parseOption().
Function Documentation
int executeAction (const struct appCommand & p_cmd)
Execute an action from the command line.
Definition at line 329 of file lx2_parse.cpp.
References appCommand::action, applyStylesheet(), closeXmlFile(), deleteNodes(), diffXmlFiles(), xmldiff_options::doNotTagDiff, duplicateDocument(), executeFile(), flushXmlFiles(), loadXmlFile(), LX_APPCOMMAND_NBPARAM, appCommand::param, printConfiguration(), recalcXmlFiles(), saveXmlFile(), charTmp::setCharTmp(), throwError(), usage(), verbose(), globalOptions::verboseLevel, XD_CLOSE, XD_DELETE, XD_DIFF, XD_DISCARD, XD_DUP, XD_EXECUTE, XD_FLUSH, XD_HELP, XD_LOAD, XD_MERGE, XD_OPTIONS, XD_PRINT, XD_PRINTCONF, XD_RECALC, XD_REM, XD_RET, XD_SAVE, XD_XSLT, XD_Exception::XDE_MEMORY_ERROR, XD_Exception::XDE_OTHER_ERROR, and XD_Exception::XDE_UNKNOWN_COMMAND.
Referenced by executeFile(), and main().
int executeFile (string scriptFileName, const map< string, string > & variables, const struct globalOptions & gOptions)
Execute file.
Parameters
scriptFileName the filename of the script to execute
variables the variables of the script
gOptions the global options of xmldiff
Returns
status code : 0 no problems -10 file not found
Definition at line 526 of file lx2_parse.cpp.
References appCommand::action, executeAction(), flushXmlFiles(), parseCommandLine(), replaceTokens(), throwError(), tokenizeCommand(), verbose(), globalOptions::verboseLevel, XD_OPTIONS, and XD_Exception::XDE_READ_ERROR.
Referenced by executeAction().
string joinVector (const vector< xmlstring > & v)
Join a vector into a string.
Definition at line 57 of file lx2_parse.cpp.
Referenced by printConfiguration().
int parseAction (string action, struct appCommand & cmd)
parseAction : parse action item
Parameters
action string containing the action
cmd command structure
Returns
0 if no error happened
Note
Set default values for actions
Definition at line 208 of file lx2_parse.cpp.
References appCommand::action, ACTION_MATCH, globalOptions::automaticSave, LX_APPCOMMAND_NBPARAM, appCommand::param, throwError(), XD_CLOSE, XD_DELETE, XD_DIFF, XD_DISCARD, XD_DUP, XD_EXECUTE, XD_FLUSH, XD_HELP, XD_LOAD, XD_MERGE, XD_NONE, XD_OPTIONS, XD_PRINT, XD_PRINTCONF, XD_RECALC, XD_REM, XD_RET, XD_SAVE, XD_XSLT, and XD_Exception::XDE_UNKNOWN_COMMAND.
Referenced by parseCommandLine().
int parseCommandLine (const vector< string > & cl, struct appCommand & opt)
parseCommandLine : parse command line
Parameters
cl arguments vector
opt [in, out] the structure that contains the result options
Returns
status code : 0 means no error
Definition at line 285 of file lx2_parse.cpp.
References appCommand::action, ARG_MATCH, LX_APPCOMMAND_NBPARAM, appCommand::param, parseAction(), parseOption(), throwError(), XD_HELP, XD_REM, and XD_Exception::XDE_TOO_MANY_ARGUMENTS.
Referenced by executeFile(), and main().
int parseOption (const string & option, const string & arg, struct globalOptions & opt)
parseOption : parse option item
Parameters
option the option
arg the option argument (must be empty if none)
opt [in, out] the structure that contains the result options
Returns
the number of element taken : 0 if an error has occured 1 if only the option was taken 2 if the argument was usefull
Definition at line 78 of file lx2_parse.cpp.
References globalOptions::automaticSave, xmldiff_options::beforeValue, globalOptions::cleanText, xmldiff_options::diff_attr, xmldiff_options::diff_ns, xmldiff_options::diff_xmlns, xmldiff_options::diffOnly, xmldiff_options::encoding, globalOptions::forceClean, globalOptions::formatPrettyPrint, xmldiff_options::ids, xmldiff_options::ignore, xmldiff_options::keepDiffOnly, xmldiff_options::mergeNsOnTop, OPT_MATCH, globalOptions::optimizeMemory, globalOptions::saveWithXslt, xmldiff_options::separator, splitVector(), xmldiff_options::tagChildsAddedRemoved, throwError(), TWO, TWO_BOOL, globalOptions::useEXSLT, globalOptions::verboseLevel, and XD_Exception::XDE_UNKNOWN_ARG.
Referenced by parseCommandLine().
void printConfiguration (const struct globalOptions & opt)
Dump current configuration.
Definition at line 615 of file lx2_parse.cpp.
References globalOptions::automaticSave, xmldiff_options::beforeValue, globalOptions::cleanText, xmldiff_options::diff_attr, xmldiff_options::diff_ns, xmldiff_options::diff_xmlns, xmldiff_options::diffOnly, xmldiff_options::encoding, globalOptions::forceClean, globalOptions::formatPrettyPrint, xmldiff_options::ids, xmldiff_options::ignore, joinVector(), xmldiff_options::keepDiffOnly, xmldiff_options::mergeNsOnTop, globalOptions::optimizeMemory, globalOptions::saveWithXslt, xmldiff_options::separator, xmldiff_options::tagChildsAddedRemoved, globalOptions::useEXSLT, and globalOptions::verboseLevel.
Referenced by executeAction().
int replaceTokens (vector< string > & tokens, map< string, string > variables)
Replace tokens by other values.
Parameters
tokens [in, out] the list of tokens
variables the list of variables name/value
Returns
the number of token replaced, or negative value on error
Definition at line 491 of file lx2_parse.cpp.
Referenced by executeFile().
void splitVector (const string arg, vector< xmlstring > & v)
Split a string into a vector.
Definition at line 43 of file lx2_parse.cpp.
Referenced by parseOption(), and setDefaultXmldiffOptions().
vector<string> tokenizeCommand (string command)
tokenizeCommand : parse command line
Parameters
command command string
Returns
the list of tokens
Definition at line 444 of file lx2_parse.cpp.
References IS_BLANK.
Referenced by executeFile().
void usage ()
Print usage.
Definition at line 562 of file lx2_parse.cpp.
Referenced by executeAction(), and main().