libxmldiff: lx2_ops.cpp File Reference
lx2_ops.cpp File Reference
#include "libxmldiff.h"
#include "lx2_ops.h"
#include "errors.h"
#include <string.h>
#include <stdarg.h>
#include <libxml/globals.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include <libxslt/xslt.h>
#include <libxslt/xsltInternals.h>
#include <libxslt/transform.h>
#include <libxslt/xsltutils.h>
#include <libexslt/exslt.h>
Macros
#define WITH_PARSERCTX
Functions
void xmlInitialize (const struct globalOptions &options)
Initialize XML Context.
void xmlFinalize (const struct globalOptions &options)
Finalize XML Context.
xmlNodePtr getXmlFile (const string &alias, const struct globalOptions &options)
Get the XML File tree.
xsltStylesheetPtr getXsltFile (const string &alias, const struct globalOptions &options)
Get the XSLT File.
int loadXmlFile (string filename, string alias, const struct globalOptions &options)
Load an XML File according to provided options.
int saveXmlFile (string filename, string alias, const struct globalOptions &options)
Save an XML File according to provided options.
void closeXmlFile (string alias, const struct globalOptions &options)
Close the XML File.
void flushXmlFiles (const struct globalOptions &options)
Flush files.
int diffXmlFiles (string beforeAlias, string afterAlias, string outputAlias, const struct globalOptions &options)
Diff Trees XML Files.
int recalcXmlFiles (string alias, const struct globalOptions &options)
Recalc an XML File according to provided options.
int deleteNodes (const string &alias, const xmlstring &xpath, const struct globalOptions &options)
Delete nodes of the file.
int duplicateDocument (const string &src, const string &dest, const struct globalOptions &options)
Duplicate Document.
int applyStylesheet (const string &xslt, const string &src, const string &dest, const char **params, const struct globalOptions &options)
Appy Stylesheet.
void setDefaultXmldiffOptions (struct appCommand &opt)
Set the defaults options.
Variables
map< string, fileInfo > loadedFiles
map< string, xsltStylesheetPtr > parsedXsltFiles
static xmlParserCtxtPtr ctxt
Macro Definition Documentation
#define WITH_PARSERCTX
Definition at line 50 of file lx2_ops.cpp.
Function Documentation
int applyStylesheet (const string & xslt, const string & src, const string & dest, const char ** params, const struct globalOptions & options)
Appy Stylesheet.
Parameters
xslt the stylesheet alias
src the source alias
dest the destination alias
params parameters to pass to the stylesheet
options Options used while diffing
Definition at line 428 of file lx2_ops.cpp.
References ctxt, getXmlFile(), getXsltFile(), loadedFiles, throwError(), globalOptions::useEXSLT, verbose(), globalOptions::verboseLevel, XD_Exception::XDE_OTHER_ERROR, XD_Exception::XDE_XSLT_ERROR, and XD_Exception::XDE_XSLT_STOPPED.
Referenced by executeAction().
void closeXmlFile (string alias, const struct globalOptions & options)
Close the XML File.
Parameters
alias The alias of the tree to be closed
options Options used while treating the file.
Definition at line 236 of file lx2_ops.cpp.
References globalOptions::automaticSave, loadedFiles, parsedXsltFiles, saveXmlFile(), verbose(), and globalOptions::verboseLevel.
Referenced by diffXmlFiles(), executeAction(), and flushXmlFiles().
int deleteNodes (const string & alias, const xmlstring & xpath, const struct globalOptions & options)
Delete nodes of the file.
Delete nodes.
Definition at line 367 of file lx2_ops.cpp.
References getXmlFile(), loadedFiles, throwError(), verbose(), globalOptions::verboseLevel, and XD_Exception::XDE_DIFF_MEMORY_ERROR.
Referenced by executeAction().
int diffXmlFiles (string beforeAlias, string afterAlias, string outputAlias, const struct globalOptions & options)
Diff Trees XML Files.
Write an XML File according to provided options.
Definition at line 282 of file lx2_ops.cpp.
References closeXmlFile(), xmldiff_options::diffOnly, diffTree(), DN_NONE, xmldiff_options::doNotFreeBeforeTreeItems, getXmlFile(), xmldiff_options::keepDiffOnly, loadedFiles, globalOptions::optimizeMemory, throwError(), verbose(), globalOptions::verboseLevel, and XD_Exception::XDE_DIFF_MEMORY_ERROR.
Referenced by executeAction().
int duplicateDocument (const string & src, const string & dest, const struct globalOptions & options)
Duplicate Document.
Duplicate document.
Definition at line 411 of file lx2_ops.cpp.
References getXmlFile(), loadedFiles, throwError(), verbose(), globalOptions::verboseLevel, and XD_Exception::XDE_DIFF_MEMORY_ERROR.
Referenced by executeAction().
void flushXmlFiles (const struct globalOptions & options)
Flush files.
Flush files Flush the loaded files record.
Definition at line 264 of file lx2_ops.cpp.
References closeXmlFile(), and loadedFiles.
Referenced by executeAction(), executeFile(), and main().
xmlNodePtr getXmlFile (const string & alias, const struct globalOptions & options)
Get the XML File tree.
Parameters
alias The alias of the tree to be returned
options Options used while treating the file.
Returns
The associated tree
Definition at line 110 of file lx2_ops.cpp.
References loadedFiles, loadXmlFile(), throwError(), and XD_Exception::XDE_ALIAS_NOT_FOUND.
Referenced by applyStylesheet(), deleteNodes(), diffXmlFiles(), duplicateDocument(), getXsltFile(), recalcXmlFiles(), and saveXmlFile().
xsltStylesheetPtr getXsltFile (const string & alias, const struct globalOptions & options)
Get the XSLT File.
Get the XSLT File tree.
Definition at line 134 of file lx2_ops.cpp.
References getXmlFile(), parsedXsltFiles, throwError(), and XD_Exception::XDE_XSLT_ERROR.
Referenced by applyStylesheet().
int loadXmlFile (string filename, string alias, const struct globalOptions & options)
Load an XML File according to provided options.
The file is appened in the loadedFiles map.
Parameters
filename The name of the file to be loaded.
alias The alias inserted in map file. If none is provided, the filename will be used
options Options used while loading the file.
Returns
0 if the file was successfully loaded
Definition at line 160 of file lx2_ops.cpp.
References cleanEmptyNodes(), globalOptions::cleanText, ctxt, fileInfo::doc, xmldiff_options::encoding, fileInfo::filename, globalOptions::forceClean, loadedFiles, fileInfo::modified, fileInfo::opened, throwError(), verbose(), globalOptions::verboseLevel, XD_Exception::XDE_READ_ERROR, and fileInfo::xslt.
Referenced by executeAction(), and getXmlFile().
int recalcXmlFiles (string alias, const struct globalOptions & options)
Recalc an XML File according to provided options.
Parameters
alias Alias for XML Tree to be relaculated
options Options used while diffing
Warning
the provided tree will be modified, whatever options could be.
Returns
the status of the recalculated tree
Definition at line 351 of file lx2_ops.cpp.
References getXmlFile(), loadedFiles, recalcTree(), verbose(), and globalOptions::verboseLevel.
Referenced by executeAction().
int saveXmlFile (string filename, string alias, const struct globalOptions & options)
Save an XML File according to provided options.
Write an XML File according to provided options.
Definition at line 206 of file lx2_ops.cpp.
References globalOptions::formatPrettyPrint, getXmlFile(), loadedFiles, globalOptions::saveWithXslt, verbose(), and globalOptions::verboseLevel.
Referenced by closeXmlFile(), and executeAction().
void setDefaultXmldiffOptions (struct appCommand & opt)
Set the defaults options.
Parameters
opt [in,out] the options reference to set.
Definition at line 469 of file lx2_ops.cpp.
References appCommand::action, globalOptions::automaticSave, xmldiff_options::beforeValue, xmldiff_options::callbackProgressionPercent, globalOptions::cleanText, xmldiff_options::diff_attr, xmldiff_options::diff_ns, xmldiff_options::diff_xmlns, xmldiff_options::diffOnly, xmldiff_options::diffQualifiersList, xmldiff_options::doNotFreeBeforeTreeItems, xmldiff_options::doNotTagDiff, xmldiff_options::encoding, globalOptions::forceClean, globalOptions::formatPrettyPrint, xmldiff_options::ids, xmldiff_options::ignore, xmldiff_options::keepDiffOnly, LX_APPCOMMAND_NBPARAM, xmldiff_options::mergeNsOnTop, globalOptions::optimizeMemory, appCommand::param, globalOptions::saveWithXslt, xmldiff_options::separator, splitVector(), xmldiff_options::tagChildsAddedRemoved, globalOptions::useEXSLT, globalOptions::verboseLevel, and XD_NONE.
Referenced by main().
void xmlFinalize (const struct globalOptions & options)
Finalize XML Context.
Definition at line 94 of file lx2_ops.cpp.
References ctxt, verbose(), and globalOptions::verboseLevel.
Referenced by main().
void xmlInitialize (const struct globalOptions & options)
Initialize XML Context.
Definition at line 82 of file lx2_ops.cpp.
References ctxt, verbose(), and globalOptions::verboseLevel.
Referenced by main().
Variable Documentation
xmlParserCtxtPtr ctxt static
Definition at line 54 of file lx2_ops.cpp.
Referenced by applyStylesheet(), loadXmlFile(), xmlFinalize(), and xmlInitialize().
map<string, fileInfo> loadedFiles
Definition at line 44 of file lx2_ops.cpp.
Referenced by applyStylesheet(), closeXmlFile(), deleteNodes(), diffXmlFiles(), duplicateDocument(), flushXmlFiles(), getXmlFile(), loadXmlFile(), recalcXmlFiles(), and saveXmlFile().
map<string, xsltStylesheetPtr> parsedXsltFiles
Definition at line 47 of file lx2_ops.cpp.
Referenced by closeXmlFile(), and getXsltFile().