libxmldiff: lx2_diff.cpp File Reference
lx2_diff.cpp File Reference
#include "libxmldiff.h"
#include "lx2_diff.h"
Data Structures
struct idNode
This struct contains the id string to be sorted, and a reference to the node.
struct IdNodeCompare
idNode comparaison function (compares the id strings)
Functions
void populate_itemlist (xmlNodePtr node, vector< idNode > &itemlist, const struct xmldiff_options &options)
Populate item list with id strings of child nodes.
int diffNode (xmlNodePtr nodeBefore, xmlNodePtr nodeAfter, const struct xmldiff_options &options)
Main diff function.
int diffTree (xmlNodePtr nodeBefore, xmlNodePtr nodeAfter, const struct xmldiff_options &options)
int recalcTree (xmlNodePtr node, const struct xmldiff_options &options)
Recalculate.
Variables
xmlstring strSpace = BAD_CAST " "
Internal Declarations ----------------------------------------—.
xmlstring strEqual = BAD_CAST "="
xmlstring strQuote = BAD_CAST "\""
xmlstring strBracketOpen = BAD_CAST "["
xmlstring strBracketClose = BAD_CAST "]"
xmlstring strAt = BAD_CAST "@"
xmlstring strSlash = BAD_CAST "/"
long beforeNodesNb
Counters.
long afterNodesNb
long beforeNodesCur
long afterNodesCur
long nodesCur
int precPercent = 0
int curPercent
struct IdNodeCompare idNodeCompare
Function Documentation
int diffNode (xmlNodePtr nodeBefore, xmlNodePtr nodeAfter, const struct xmldiff_options & options)
Main diff function.
This function performs the diff between two nodes, and modify the nodeAfter to reflect the changes (diff:status, add elements,...) It also free nodeBefore as much as possible, to save memory. The algorithm is described in the function.
Parameters
nodeBefore : the node of the first file
nodeAfter : the node of the second file
options : the diff options (see xmldiff_options)
Returns
the status of the diff (
See Also
DN_STATUS) or error code : -1 : unable to create some structures, should be a memory problem.
Warning
nodeBefore and nodeAfter are affected by this function.
Definition at line 169 of file lx2_diff.cpp.
References afterNodesCur, afterNodesNb, beforeNodesCur, beforeNodesNb, xmldiff_options::beforeValue, xmldiff_options::callbackProgressionPercent, xmldiff_options::cbProgressionArg, curPercent, xmldiff_options::diff_attr, xmldiff_options::diff_xmlns, xmldiff_options::diffOnly, xmldiff_options::diffQualifiersList, DN_ADDED, DN_BELOW, DN_MODIFIED, DN_NONE, DN_REMOVED, xmldiff_options::doNotFreeBeforeTreeItems, xmldiff_options::doNotTagDiff, getNodeTextOnly(), xmldiff_options::ignore, xmldiff_options::keepDiffOnly, matchNode(), nodesCur, populate_itemlist(), precPercent, xmldiff_options::separator, setAttributeToAllChilds(), xmldiff_options::tagChildsAddedRemoved, throwError(), and XD_Exception::XDE_NAMESPACE_PROBLEM.
Referenced by diffTree().
int diffTree (xmlNodePtr nodeBefore, xmlNodePtr nodeAfter, const struct xmldiff_options & options)
Definition at line 437 of file lx2_diff.cpp.
References afterNodesCur, afterNodesNb, beforeNodesCur, beforeNodesNb, xmldiff_options::callbackProgressionPercent, xmldiff_options::cbProgressionArg, countElementNodes(), createNamespaceOnTop(), xmldiff_options::diff_ns, xmldiff_options::diff_xmlns, diffNode(), xmldiff_options::diffOnly, xmldiff_options::mergeNsOnTop, nodesCur, precPercent, throwError(), and XD_Exception::XDE_NAMESPACE_PROBLEM.
Referenced by diffXmlFiles().
void populate_itemlist (xmlNodePtr node, vector< idNode > & itemlist, const struct xmldiff_options & options)
Populate item list with id strings of child nodes.
This list will be populated with the name of the node and attributes/elements contained in the ids list, and then sorted.
Parameters
node : the node to inspect
itemlist : the list to populate
options : diff options
Definition at line 74 of file lx2_diff.cpp.
References getFirstChildByTagName(), getNodeTextOnly(), idNode::id, idNodeCompare, xmldiff_options::ids, xmldiff_options::ignore, matchNode(), idNode::node, strEqual, strQuote, and strSpace.
Referenced by diffNode().
int recalcTree (xmlNodePtr node, const struct xmldiff_options & options)
Recalculate.
Definition at line 489 of file lx2_diff.cpp.
References xmldiff_options::beforeValue, xmldiff_options::diff_attr, xmldiff_options::diff_ns, xmldiff_options::diff_xmlns, xmldiff_options::diffOnly, xmldiff_options::diffQualifiersList, DN_ADDED, DN_BELOW, DN_MODIFIED, DN_NONE, DN_REMOVED, recalcTree(), and xmldiff_options::separator.
Referenced by recalcTree(), and recalcXmlFiles().
Variable Documentation
long afterNodesCur
Definition at line 45 of file lx2_diff.cpp.
Referenced by diffNode(), and diffTree().
long afterNodesNb
Definition at line 43 of file lx2_diff.cpp.
Referenced by diffNode(), and diffTree().
long beforeNodesCur
Definition at line 44 of file lx2_diff.cpp.
Referenced by diffNode(), and diffTree().
long beforeNodesNb
Counters.
Definition at line 42 of file lx2_diff.cpp.
Referenced by diffNode(), and diffTree().
int curPercent
Definition at line 47 of file lx2_diff.cpp.
Referenced by diffNode().
struct IdNodeCompare idNodeCompare
Referenced by populate_itemlist().
long nodesCur
Definition at line 46 of file lx2_diff.cpp.
Referenced by diffNode(), and diffTree().
int precPercent = 0
Definition at line 47 of file lx2_diff.cpp.
Referenced by diffNode(), and diffTree().
xmlstring strAt = BAD_CAST "@"
Definition at line 38 of file lx2_diff.cpp.
xmlstring strBracketClose = BAD_CAST "]"
Definition at line 37 of file lx2_diff.cpp.
xmlstring strBracketOpen = BAD_CAST "["
Definition at line 36 of file lx2_diff.cpp.
xmlstring strEqual = BAD_CAST "="
Definition at line 34 of file lx2_diff.cpp.
Referenced by populate_itemlist().
xmlstring strQuote = BAD_CAST "\""
Definition at line 35 of file lx2_diff.cpp.
Referenced by populate_itemlist().
xmlstring strSlash = BAD_CAST "/"
Definition at line 39 of file lx2_diff.cpp.
xmlstring strSpace = BAD_CAST " "
Internal Declarations ----------------------------------------—.
Definition at line 33 of file lx2_diff.cpp.
Referenced by populate_itemlist().