libxmldiff: lx2_util.cpp File Reference
lx2_util.cpp File Reference
#include "libxmldiff.h"
#include "lx2_util.h"
Functions
xmlstring getNodeTextOnly (xmlNodePtr node, bool cdata)
Get only text nodes of node, and not all text nodes of this node and subnodes.
xmlNodePtr getFirstChildByTagName (xmlNodePtr node, const xmlstring name)
Get the first child with this tagname : used for id elements.
void setAttributeToAllChilds (const xmlNodePtr node, const xmlstring &ns, const xmlstring &name, const xmlstring &value, const bool toAll)
Set diff;status attribute.
void cleanEmptyNodes (xmlNodePtr node)
Clean the tree of blank text nodes.
void cleanPrivateTag (xmlNodePtr node)
Clean the _private tag of the tree.
long countElementNodes (xmlNodePtr node)
Count XML_ELEMENT_NODE nodes.
int createNamespaceOnTop (xmlNodePtr node, const xmlChar *href, const xmlChar *prefix)
createNamespaceOnTop Create the namespace on top of document of the provided node
bool LIBXMLUTIL_API matchNode (xmlNodePtr node, vector< xmlstring > list)
matchNode Check if a given node matched a lists of names
Function Documentation
void cleanEmptyNodes (xmlNodePtr node)
Clean the tree of blank text nodes.
cleanEmptyNodes Clean empty nodes from the tree.
Definition at line 90 of file lx2_util.cpp.
References cleanEmptyNodes().
Referenced by cleanEmptyNodes(), and loadXmlFile().
void cleanPrivateTag (xmlNodePtr node)
Clean the _private tag of the tree.
cleanPrivateTag Set to NULL the _private tag of all nodes of the tree.
Definition at line 127 of file lx2_util.cpp.
References cleanPrivateTag().
Referenced by cleanPrivateTag().
long countElementNodes (xmlNodePtr node)
Count XML_ELEMENT_NODE nodes.
countNodes Count the number of element nodes
Definition at line 141 of file lx2_util.cpp.
References countElementNodes().
Referenced by countElementNodes(), and diffTree().
int createNamespaceOnTop (xmlNodePtr node, const xmlChar * href, const xmlChar * prefix)
createNamespaceOnTop Create the namespace on top of document of the provided node
Parameters
node the node
href the href of the namespace to create
prefix the prefix to use in this document for this namespace
Returns
the number of successfully created namespace To get the created namespace, use searchNamespace...
Definition at line 163 of file lx2_util.cpp.
Referenced by diffTree().
xmlNodePtr getFirstChildByTagName (xmlNodePtr node, const xmlstring name)
Get the first child with this tagname : used for id elements.
getFirstChildByTagName Returns the first child of the children list having its tag name equal to the one provided
Definition at line 52 of file lx2_util.cpp.
Referenced by populate_itemlist().
xmlstring getNodeTextOnly (xmlNodePtr node, bool cdata)
Get only text nodes of node, and not all text nodes of this node and subnodes.
getNodeTextOnly Get text of the current node, without taking subnodes as does get_text()
Definition at line 27 of file lx2_util.cpp.
Referenced by diffNode(), and populate_itemlist().
bool LIBXMLUTIL_API matchNode (xmlNodePtr node, vector< xmlstring > list)
matchNode Check if a given node matched a lists of names
Parameters
node the node to match
list list of match expressions (no XPath nor regex for now)
Returns
true if the node matches
Definition at line 183 of file lx2_util.cpp.
Referenced by diffNode(), and populate_itemlist().
void setAttributeToAllChilds (const xmlNodePtr node, const xmlstring & ns, const xmlstring & name, const xmlstring & value, const bool toAll)
Set diff;status attribute.
setAttributeToAllChilds Set the provided property to all children of the current element.
Definition at line 70 of file lx2_util.cpp.
References setAttributeToAllChilds().
Referenced by diffNode(), and setAttributeToAllChilds().