libxmldiff: errors.cpp File Reference
errors.cpp File Reference
#include "errors.h"
#include "stdio.h"
#include "stdarg.h"
Functions
void throwError (int type, const char *str,...)
XML Diff Exception Helper Function.
void verbose (int prio, int level, char *str,...)
Function Documentation
void throwError (int type, const char * str, ...)
XML Diff Exception Helper Function.
Definition at line 40 of file errors.cpp.
Referenced by applyStylesheet(), deleteNodes(), diffNode(), diffTree(), diffXmlFiles(), duplicateDocument(), executeAction(), executeFile(), getXmlFile(), getXsltFile(), loadXmlFile(), parseAction(), parseCommandLine(), and parseOption().
void verbose (int prio, int level, char * str, ...)
Definition at line 51 of file errors.cpp.
Referenced by applyStylesheet(), closeXmlFile(), deleteNodes(), diffXmlFiles(), duplicateDocument(), executeAction(), executeFile(), loadXmlFile(), main(), recalcXmlFiles(), saveXmlFile(), xmlFinalize(), and xmlInitialize().