libxmldiff: lx2_ops.h File Reference
lx2_ops.h File Reference
#include "libxmldiff.h"
#include <map>
#include <string>
#include "lx2_util.h"
#include "lx2_diff.h"
#include <libxslt/transform.h>
Data Structures
struct globalOptions
struct appCommand
struct fileInfo
Macros
#define LX_APPCOMMAND_NBPARAM 25
Enumerations
enum actType {
XD_NONE = 0, XD_OPTIONS, XD_DIFF, XD_MERGE,
XD_RECALC, XD_EXECUTE, XD_LOAD, XD_SAVE,
XD_CLOSE, XD_FLUSH, XD_PRINT, XD_DELETE,
XD_DUP, XD_XSLT, XD_REM, XD_DISCARD,
XD_PRINTCONF, XD_HELP, XD_RET
}
Functions
void LIBXMLDIFF_API xmlInitialize (const struct globalOptions &options)
Initialize XML Context.
void LIBXMLDIFF_API xmlFinalize (const struct globalOptions &options)
Finalize XML Context.
int LIBXMLDIFF_API loadXmlFile (string filename, string alias, const struct globalOptions &options)
Load an XML File according to provided options.
int LIBXMLDIFF_API saveXmlFile (string filename, string alias, const struct globalOptions &options)
Write an XML File according to provided options.
xmlNodePtr LIBXMLDIFF_API getXmlFile (const string &alias, const struct globalOptions &options)
Get the XML File tree.
xsltStylesheetPtr LIBXMLDIFF_API getXsltFile (const string &alias, const struct globalOptions &options)
Get the XSLT File tree.
void LIBXMLDIFF_API flushXmlFiles (const struct globalOptions &options)
Flush files Flush the loaded files record.
void LIBXMLDIFF_API closeXmlFile (string alias, const struct globalOptions &options)
Close the XML File.
int LIBXMLDIFF_API diffXmlFiles (string beforeAlias, string afterAlias, string outputAlias, const struct globalOptions &options)
Write an XML File according to provided options.
int LIBXMLDIFF_API recalcXmlFiles (string alias, const struct globalOptions &options)
Recalc an XML File according to provided options.
int LIBXMLDIFF_API deleteNodes (const string &alias, const xmlstring &xpath, const struct globalOptions &options)
Delete nodes.
int LIBXMLDIFF_API duplicateDocument (const string &src, const string &dest, const struct globalOptions &options)
Duplicate document.
int LIBXMLDIFF_API applyStylesheet (const string &xslt, const string &src, const string &dest, const char **params, const struct globalOptions &options)
Appy Stylesheet.
void LIBXMLDIFF_API setDefaultXmldiffOptions (struct appCommand &opt)
Set the defaults options.
Variables
map< string, fileInfo > loadedFiles
Macro Definition Documentation
#define LX_APPCOMMAND_NBPARAM 25
Definition at line 95 of file lx2_ops.h.
Referenced by executeAction(), parseAction(), parseCommandLine(), and setDefaultXmldiffOptions().
Enumeration Type Documentation
enum actType
Enumerator
XD_NONE
XD_OPTIONS
XD_DIFF
XD_MERGE
XD_RECALC
XD_EXECUTE
XD_LOAD
XD_SAVE
XD_CLOSE
XD_FLUSH
XD_PRINT
XD_DELETE
XD_DUP
XD_XSLT
XD_REM
XD_DISCARD
XD_PRINTCONF
XD_HELP
XD_RET
Definition at line 45 of file lx2_ops.h.
Function Documentation
int LIBXMLDIFF_API applyStylesheet (const string & xslt, const string & src, const string & dest, const char ** params, const struct globalOptions & options)
Appy Stylesheet.
Parameters
xslt the stylesheet alias
src the source alias
dest the destination alias
params parameters to pass to the stylesheet
options Options used while diffing
Definition at line 428 of file lx2_ops.cpp.
References ctxt, getXmlFile(), getXsltFile(), loadedFiles, throwError(), globalOptions::useEXSLT, verbose(), globalOptions::verboseLevel, XD_Exception::XDE_OTHER_ERROR, XD_Exception::XDE_XSLT_ERROR, and XD_Exception::XDE_XSLT_STOPPED.
Referenced by executeAction().
void LIBXMLDIFF_API closeXmlFile (string alias, const struct globalOptions & options)
Close the XML File.
Parameters
alias The alias of the tree to be closed
options Options used while treating the file.
Definition at line 236 of file lx2_ops.cpp.
References globalOptions::automaticSave, loadedFiles, parsedXsltFiles, saveXmlFile(), verbose(), and globalOptions::verboseLevel.
Referenced by diffXmlFiles(), executeAction(), and flushXmlFiles().
int LIBXMLDIFF_API deleteNodes (const string & alias, const xmlstring & xpath, const struct globalOptions & options)
Delete nodes.
Parameters
alias of the file to modify
xpath the xpath expression of node set to be deleted
options Options used while diffing
Delete nodes.
Definition at line 367 of file lx2_ops.cpp.
References getXmlFile(), loadedFiles, throwError(), verbose(), globalOptions::verboseLevel, and XD_Exception::XDE_DIFF_MEMORY_ERROR.
Referenced by executeAction().
int LIBXMLDIFF_API diffXmlFiles (string beforeAlias, string afterAlias, string outputAlias, const struct globalOptions & options)
Write an XML File according to provided options.
Parameters
beforeAlias Alias/Filename for before XML Tree
afterAlias Alias/Filename for after XML Tree
outputAlias Alias/Filename for output XML Tree
options Options used while diffing
Returns
the result of the diff (DN_NONE means no modifications, else the tree has been modified)
Write an XML File according to provided options.
Definition at line 282 of file lx2_ops.cpp.
References closeXmlFile(), xmldiff_options::diffOnly, diffTree(), DN_NONE, xmldiff_options::doNotFreeBeforeTreeItems, getXmlFile(), xmldiff_options::keepDiffOnly, loadedFiles, globalOptions::optimizeMemory, throwError(), verbose(), globalOptions::verboseLevel, and XD_Exception::XDE_DIFF_MEMORY_ERROR.
Referenced by executeAction().
int LIBXMLDIFF_API duplicateDocument (const string & src, const string & dest, const struct globalOptions & options)
Duplicate document.
Parameters
src alias of source document
dest alias of destination document
options Options used while diffing
Duplicate document.
Definition at line 411 of file lx2_ops.cpp.
References getXmlFile(), loadedFiles, throwError(), verbose(), globalOptions::verboseLevel, and XD_Exception::XDE_DIFF_MEMORY_ERROR.
Referenced by executeAction().
void LIBXMLDIFF_API flushXmlFiles (const struct globalOptions & options)
Flush files Flush the loaded files record.
Parameters
options Options used while treating the file.
Flush files Flush the loaded files record.
Definition at line 264 of file lx2_ops.cpp.
References closeXmlFile(), and loadedFiles.
Referenced by executeAction(), executeFile(), and main().
xmlNodePtr LIBXMLDIFF_API getXmlFile (const string & alias, const struct globalOptions & options)
Get the XML File tree.
Parameters
alias The alias of the tree to be returned
options Options used while treating the file.
Returns
The associated tree
Definition at line 110 of file lx2_ops.cpp.
References loadedFiles, loadXmlFile(), throwError(), and XD_Exception::XDE_ALIAS_NOT_FOUND.
Referenced by applyStylesheet(), deleteNodes(), diffXmlFiles(), duplicateDocument(), getXsltFile(), recalcXmlFiles(), and saveXmlFile().
xsltStylesheetPtr LIBXMLDIFF_API getXsltFile (const string & alias, const struct globalOptions & options)
Get the XSLT File tree.
Parameters
alias The alias of the tree to be returned
options Options used while treating the file.
Returns
The associated tree
Get the XSLT File tree.
Definition at line 134 of file lx2_ops.cpp.
References getXmlFile(), parsedXsltFiles, throwError(), and XD_Exception::XDE_XSLT_ERROR.
Referenced by applyStylesheet().
int LIBXMLDIFF_API loadXmlFile (string filename, string alias, const struct globalOptions & options)
Load an XML File according to provided options.
The file is appened in the loadedFiles map.
Parameters
filename The name of the file to be loaded.
alias The alias inserted in map file. If none is provided, the filename will be used
options Options used while loading the file.
Returns
0 if the file was successfully loaded
Definition at line 160 of file lx2_ops.cpp.
References cleanEmptyNodes(), globalOptions::cleanText, ctxt, fileInfo::doc, xmldiff_options::encoding, fileInfo::filename, globalOptions::forceClean, loadedFiles, fileInfo::modified, fileInfo::opened, throwError(), verbose(), globalOptions::verboseLevel, XD_Exception::XDE_READ_ERROR, and fileInfo::xslt.
Referenced by executeAction(), and getXmlFile().
int LIBXMLDIFF_API recalcXmlFiles (string alias, const struct globalOptions & options)
Recalc an XML File according to provided options.
Parameters
alias Alias for XML Tree to be relaculated
options Options used while diffing
Warning
the provided tree will be modified, whatever options could be.
Returns
the status of the recalculated tree
Definition at line 351 of file lx2_ops.cpp.
References getXmlFile(), loadedFiles, recalcTree(), verbose(), and globalOptions::verboseLevel.
Referenced by executeAction().
int LIBXMLDIFF_API saveXmlFile (string filename, string alias, const struct globalOptions & options)
Write an XML File according to provided options.
Parameters
filename The name of the file to be loaded.
alias The alias of the tree to save inserted in map file.
options Options used while saving the file.
Returns
0 if the file was successfully saved
Write an XML File according to provided options.
Definition at line 206 of file lx2_ops.cpp.
References globalOptions::formatPrettyPrint, getXmlFile(), loadedFiles, globalOptions::saveWithXslt, verbose(), and globalOptions::verboseLevel.
Referenced by closeXmlFile(), and executeAction().
void LIBXMLDIFF_API setDefaultXmldiffOptions (struct appCommand & opt)
Set the defaults options.
Parameters
opt [in,out] the options reference to set.
Definition at line 469 of file lx2_ops.cpp.
References appCommand::action, globalOptions::automaticSave, xmldiff_options::beforeValue, xmldiff_options::callbackProgressionPercent, globalOptions::cleanText, xmldiff_options::diff_attr, xmldiff_options::diff_ns, xmldiff_options::diff_xmlns, xmldiff_options::diffOnly, xmldiff_options::diffQualifiersList, xmldiff_options::doNotFreeBeforeTreeItems, xmldiff_options::doNotTagDiff, xmldiff_options::encoding, globalOptions::forceClean, globalOptions::formatPrettyPrint, xmldiff_options::ids, xmldiff_options::ignore, xmldiff_options::keepDiffOnly, LX_APPCOMMAND_NBPARAM, xmldiff_options::mergeNsOnTop, globalOptions::optimizeMemory, appCommand::param, globalOptions::saveWithXslt, xmldiff_options::separator, splitVector(), xmldiff_options::tagChildsAddedRemoved, globalOptions::useEXSLT, globalOptions::verboseLevel, and XD_NONE.
Referenced by main().
void LIBXMLDIFF_API xmlFinalize (const struct globalOptions & options)
Finalize XML Context.
Definition at line 94 of file lx2_ops.cpp.
References ctxt, verbose(), and globalOptions::verboseLevel.
Referenced by main().
void LIBXMLDIFF_API xmlInitialize (const struct globalOptions & options)
Initialize XML Context.
Definition at line 82 of file lx2_ops.cpp.
References ctxt, verbose(), and globalOptions::verboseLevel.
Referenced by main().
Variable Documentation
map<string, fileInfo> loadedFiles
Definition at line 44 of file lx2_ops.cpp.
Referenced by applyStylesheet(), closeXmlFile(), deleteNodes(), diffXmlFiles(), duplicateDocument(), flushXmlFiles(), getXmlFile(), loadXmlFile(), recalcXmlFiles(), and saveXmlFile().