libxmldiff: lx2_diff.h File Reference
lx2_diff.h File Reference
#include "libxmldiff.h"
#include "lx2_util.h"
#include <string>
#include <vector>
#include <iostream>
#include <algorithm>
Data Structures
struct xmldiff_options
Enumerations
enum DN_STATUS {
DN_UNKNOWN = 0, DN_ADDED, DN_REMOVED, DN_MODIFIED,
DN_BELOW, DN_NONE
}
Status List.
Functions
int LIBXMLDIFF_API diffTree (xmlNodePtr nodeBefore, xmlNodePtr nodeAfter, const struct xmldiff_options &options)
int LIBXMLDIFF_API recalcTree (xmlNodePtr node, const struct xmldiff_options &options)
Recalculate.
Enumeration Type Documentation
enum DN_STATUS
Status List.
Enumerator
DN_UNKNOWN
DN_ADDED
DN_REMOVED
DN_MODIFIED
DN_BELOW
DN_NONE
Definition at line 44 of file lx2_diff.h.
Function Documentation
int LIBXMLDIFF_API diffTree (xmlNodePtr nodeBefore, xmlNodePtr nodeAfter, const struct xmldiff_options & options)
Definition at line 437 of file lx2_diff.cpp.
References afterNodesCur, afterNodesNb, beforeNodesCur, beforeNodesNb, xmldiff_options::callbackProgressionPercent, xmldiff_options::cbProgressionArg, countElementNodes(), createNamespaceOnTop(), xmldiff_options::diff_ns, xmldiff_options::diff_xmlns, diffNode(), xmldiff_options::diffOnly, xmldiff_options::mergeNsOnTop, nodesCur, precPercent, throwError(), and XD_Exception::XDE_NAMESPACE_PROBLEM.
Referenced by diffXmlFiles().
int LIBXMLDIFF_API recalcTree (xmlNodePtr node, const struct xmldiff_options & options)
Recalculate.
Definition at line 489 of file lx2_diff.cpp.
References xmldiff_options::beforeValue, xmldiff_options::diff_attr, xmldiff_options::diff_ns, xmldiff_options::diff_xmlns, xmldiff_options::diffOnly, xmldiff_options::diffQualifiersList, DN_ADDED, DN_BELOW, DN_MODIFIED, DN_NONE, DN_REMOVED, recalcTree(), and xmldiff_options::separator.
Referenced by recalcTree(), and recalcXmlFiles().